name: dev
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *'
# TODO: 将不同的模块分离开 编译模块，定时服务模块
jobs:
  dev:
    name: build and run by ts-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn
      - run: yarn dev
        env:
          PASSWORD: ${{secrets.PASSWORD}}
          USERNAME: ${{secrets.USERNAME}}
